// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the trust level for a project directory.
 * This determines the approval policy and sandbox mode applied.
 */
export type TrustLevel = "trusted" | "untrusted";
